### PR TITLE
Added Gnosis-Safe integration

### PR DESCRIPTION
**Pull request by thrilok209**
1) Get Gnosis safes from address => `await dsa.gnosisSafe.getSafeAddresses(ADDR)`
2) To cast spells => `await dsa.cast(spells).then(console.log)`
3) Before casting spells for multi sig, need to set the instance for safe address => `dsa.setInstance(dsaId, {gnosisSafe: SAFE_ADDR})`
4) To get a particular multi-sig owners => `await dsa.gnosisSafe.getSafeOwners(SAFE_ADDR)`
5) To get auth types of dsa => `await dsa.account.getAuthoritiesTypes(DSA_ADDR)`

### CODE REVIEW

**Comment by leckylao** [comment]
image
Just saw this and I have put logic in submitTx to getSafeAddress. So setInstance is optional
image

**Comment by Sowmayjain** [comment]
Super cool!

Point 3 -> what about making it part of normal `dsa.setInstance({gnosisSafe: "0x..."})` - something like that.

Point 2 -> once we do the `.setInstance()` (any kind), why do we need to pass the "1" as parameter in cast() - it should internally figure out that as gnosisSafe instance is already assigned, initiate the gnosisSafe call.

**Comment by Sowmayjain** [comment]
> image
> Just saw this and I have put logic in submitTx to getSafeAddress. So setInstance is optional
> image

What if an address have multiple gnosisSafe as authority? - we do have the optionality but it's good if we deliberately set gnosisSafe address. Do correct me if not accurate.

**Comment by leckylao** [comment]
> > image
> > Just saw this and I have put logic in submitTx to getSafeAddress. So setInstance is optional
> > image
> 
> What if an address have multiple gnosisSafe as authority? - we do have the optionality but it's good if we deliberately set gnosisSafe address. Do correct me if not accurate.

When there's multiple safe addresses. Default just take the first one. So setInstance is optionally that you could set to other one. I guess similar to you could have multiple DSA addresses and just default to pick the first one

**Comment by Sowmayjain** [comment]
Yess - although, we need to give them option to switch gSafe (if they have multiple). Right now, there’s way to switch DSA - let me see how it could go on dapp with multi-sign.

**Comment by leckylao** [comment]
> Yess - although, we need to give them option to switch gSafe (if they have multiple). Right now, there’s way to switch DSA - let me see how it could go on dapp with multi-sign.

That's where you use setInstance to set the safe address you want

**Pull request merged**
